### ISSUE TITLE
Stdout option has been removed

### ISSUE THREAD

**Issue by ArthurHlt** [pampa/rutil#4]
Any reason that's this option has been removed ?
It's actually my own project: https://github.com/Orange-OpenSource/db-dumper-service 

I saw it has been removed from your last commit but your readme is not up to date

**Comment by pampa** [comment]
The dump file has a header with the number of keys, this is the number reported by redis "keys *' command, when i get the key names initially.
Some keys might expire or get deleted while the programm is running, so the actual number of keys dumped might be different from the number reported by "keys *", when finishing the dump i have to seek to the beginning of the file and update the header with the correct number.

Since you can't seek to the beginning of stdout or to the end of stdin, i thought that remiving this option was best. It didnt make much sense to me to dump a binary format to stdout anyway.

If you have a better idea how to fix this, i'm all ears.

**Comment by ArthurHlt** [comment]
I'm not an expert in redis at all, but is it necessary to have the number of keys? I guess it's easier to know this number to browse all key in your code ?
Maybe redis have a lock mechanism to create a dump ? It doesn't seems that redis have it natively but some people implemented a lock mechanism: https://www.npmjs.com/package/redis-lock or https://github.com/promiscuous-io/robust-redis-lock

Obviously, use stdout to show binaries in a terminal is stupid, but if you want to pipe with something else it's needed. In my case, i want to upload binaries from rutil on a storage service like Amazon S3 but i do not want to create a file on filesystem (because i'm on a cloud and filesystem is small and not intended to store anything), i want to retrieve a stream which will go in memory and will be directly sent to my storage service.

You can think that i can be an isolated case but if you remove stream you also add more latency, imagine that your user have a huge redis database and he wants to pass data to another program for doing something else. He will have to wait to create the file globally and after pass it to his program, if he can stream this it will go slightly faster mainly because memory is faster than filesystem but also cause he doesn't have to wait this creation.

By the way, mongodb dump binary too but you can use stdout as an output (option: [--archive](https://www.mongodb.com/blog/post/archiving-and-compression-in-mongodb-tools) )

**Comment by pampa** [comment]
The number of keys is required for the nice progressbars on dump and restore. I kind of like the progressbars and dont want to break them, but i see your point that sometimes dumping to stdout is preferable than dumping to a file.

So, the best solution i could come up with, is a separate command `rutil pipe`. It dumps the contents of a redis database in a format, that is compatible with `redis-cli --pipe`. There is no unpipe in rutil, to restore the file you have to use redis-cli.

```
$ rutil pipe > redis.txt
$ redis-cli flushdb
OK
$ cat redis.txt | redis-cli --pipe
All data transferred. Waiting for the last reply...
Last reply received from server.
errors: 0, replies: 371665
```

I hope this will cover your use case
